- name: Copy hosts file to Axon hosts
  hosts: axon
  tasks:
    - name: Copy hosts to /etc/hosts
      become: true
      copy:
        src: files/hosts
        dest: /etc/hosts

- name: AxonServer.zip should be unzipped
  hosts: localhost
  tasks:
    - name: Make folder to extract to
      file:
        path: temp/server_files
        state: directory
    - name: Extract ./files/AxonServer.zip into temp/server_files/
      unarchive:
        src: ../../files/AxonServer.zip
        dest: temp/server_files
        list_files: true
      register: extracted_files

# https://forum.ansible.com/t/unpacking-a-zip-with-variably-named-root-folder/2805/2
# Depends on variable set in previous Playbook.
- name: Upload unzipped files to Axon hosts
  hosts: axon
  tasks:
    - name: Copy over the files to the Axon hosts
      become: true
      copy:
        src: "temp/server_files/{{hostvars.localhost.extracted_files.files[0]}}"
        dest: "/home/axon"

- name: Use custom properties file
  hosts: axon
  tasks:
    - name: Copy custom properties file to the Axon hosts
      become: true
      copy:
        src: files/axonserver.properties
        dest: "/home/axon"

# https://wiki.debian.org/Java
- name: Install java runtime on Axon hosts
  hosts: axon
  tasks:
    - name: Install Java Runtime Environment
      become: true
      package:
        name: default-jre
        state: present

- name: Configure Axon users
  hosts: axon
  become: true
  tasks:
    - name: Ensure group "axon" exists
      group:
        name: axon
        state: present
    - name: Create axon user
      user:
        name: axon
        group: axon
        uid: 10000
        password: "!"
        home: "/home/axon"
    - name: Set home folder access rights
      file:
        path: "/home/axon"
        owner: axon
        mode: "0750"

- name: Set up Axon systemd service
  hosts: axon
  tasks:
    - name: Copy service file to host
      become: true
      copy:
        src: files/axon.service
        dest: /etc/systemd/system
      notify:
        - Reload systemd
  handlers:
    - name: Reload systemd
      systemd_service:
        daemon_reload: true

- name: Ensure Axon services are running
  hosts: axon
  tasks:
    - name: Enable and start axon systemd service
      become: true
      systemd_service:
        name: axon
        enabled: yes
        state: started


# - name: Register nodes to a cluster
#   hosts: axon
#   tasks:
#     - name: Register node to master
#       command:
#         run: java -jar axoniq-cli.jar register-node -h axon01
